services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=trial_role_project
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: my_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trial_role_project
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: